### ISSUE TITLE
run containers as non-root

### ISSUE THREAD

**Issue by lpasquali** [geosolutions-it/eumetsat-EOWS#474]
This is an issue on our kanban to track customers Jira [one](https://cgi-pathfinders.atlassian.net/browse/AH-4)

Containers of EUMETView NG shall not run as root

our technical note for reference of what to be done [here](https://docs.google.com/document/d/1KOG3FEDRoYlQ7dJMSMhdvAd0cCR9CD243VSyNUugr54/edit)

**Comment by lpasquali** [comment]
@randomorder as we spoke the cron daemon does not work well as non root, in order to find a solution, I would propose to use python module "schedule", I tested a script done as per the module maintainer example and it does its work and handles very similar arguments, old piece of [manifest template](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/templates/statefulsets/mapcache-set.yaml) was like:
```yaml
      - name: mapcache-cleancache
        image: "{{ .Values.mapcache.cleancache.image.repository }}:{{ .Values.mapcache.cleancache.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: 
        - start-cron 
        args:
        - '\{{ required "missing value" .Values.mapcache.cleancache.schedule | replace " " " \\" }} /home/cleancache2.sh /cache /home/layers.properties > /proc/1/fd/1 2>&1'
        volumeMounts:
        - name: mapcache-tiles
          mountPath: /cache
        - name: mapcache-cleancache-layers
          mountPath: /home/layers.properties
          subPath: layers.properties
```
new manfiest becomes:

```yaml
      - name: mapcache-cleancache
        image: "{{ .Values.mapcache.cleancache.image.repository }}:{{ .Values.mapcache.cleancache.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: 
        - scheduler.py 
        args: ['{{ required "missing value" .Values.mapcache.cleancache.schedule}}','/home/cleancache2.sh /cache /home/layers.properties']
        volumeMounts:
        - name: mapcache-tiles
          mountPath: /cache
        - name: mapcache-cleancache-layers
          mountPath: /home/layers.properties
          subPath: layers.properties
```

also [values.yaml](https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/values.yaml) will change:
```yaml
  cleancache:
    image:
      repository: harbor.eumetsat.int/ext-wms/mapcache-cleancache
      tag: 1.2
    schedule: "1:00"
```    

scheduler.py would be:

```
#!/usr/bin/env python3
import schedule
import time
import subprocess
import sys
import os

def convert(lst):
    return ' '.join(lst)

def job():
    os.system(BASH_COMMAND)

RUN_HOUR = sys.argv[1]
BASH_COMMAND = convert(sys.argv[2:])
print(RUN_HOUR)
print(BASH_COMMAND)
schedule.every().day.at(RUN_HOUR).do(job)

while True:
    schedule.run_pending()
    time.sleep(1)
```
Dockerfile would be:
```
FROM debian:buster

ARG ID=99
ARG GID=99
RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN pip3 install schedule
# cleancache: for each layer, "find" folders and "rm" <layer>
COPY cleancache.sh /home 
# cleancache2: group layers by rettime and "rm" <list folders>
COPY cleancache2.sh /home
COPY layers.properties /home
COPY scheduler.py /home

USER ${ID}:${GID}
CMD ["/home/scheduler.py"]
```
